server:
  port: 8090

jwt:
    secret: 'b3d5775b5f624a4a92207d980e83d3ee@@@!!!%%$$__))__)_'


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

